"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'
import { configureBoneyard } from 'boneyard-js/react'

import _studio_startup from './studio-startup.bones.json'
import _voiceover_history from './voiceover-history.bones.json'

configureBoneyard({"color":"var(--bg-raised)","darkColor":"var(--bg-raised)","animate":"shimmer","shimmerColor":"var(--bg-hover)","darkShimmerColor":"var(--bg-hover)","speed":"1.2s","shimmerAngle":110})

registerBones({
  "studio-startup": _studio_startup,
  "voiceover-history": _voiceover_history,
})
