#!/usr/bin/env python3
"""Compile the launcher splash's Tailwind CSS and inline it into a Python module.

The launcher's loading screen is served from a Python string over a loopback
socket by a frozen exe. It has to paint when nothing else in the product is
up -- no backend, and frequently no network, because the most common reason
someone is staring at it is a first run that is still downloading the model.

That rules out Tailwind's Play CDN, which fetches a compiler from jsdelivr at
runtime: offline it would render the splash completely unstyled, at the one
moment the splash exists for. So this surface compiles ahead of time.

    python scripts/build_splash.py            # generate
    python scripts/build_splash.py --check    # fail if the output is stale

Reads  launcher/splash.html  +  launcher/splash.css
Writes launcher/_splash.py   (committed, so a build without npm still works)

_splash.py is a MODULE, not a data file, and that is deliberate:
launcher.spec declares `datas=[]` and scripts/check_desktop_port.py relies on
that. PyInstaller follows imports, so a generated .py is bundled with no spec
change at all.
"""
from __future__ import annotations

import argparse
import hashlib
import re
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
LAUNCHER = ROOT / "launcher"
HTML = LAUNCHER / "splash.html"
CSS = LAUNCHER / "splash.css"
OUT = LAUNCHER / "_splash.py"
FRONTEND = ROOT / "frontend"

PLACEHOLDER = "__SPLASH_CSS__"


def tailwind_cli() -> list[str]:
    """The CLI from the frontend's node_modules. Not a global install."""
    for name in ("tailwindcss.cmd", "tailwindcss"):
        exe = FRONTEND / "node_modules" / ".bin" / name
        if exe.exists():
            return [str(exe)]
    npx = shutil.which("npx")
    if npx:
        return [npx, "--no-install", "@tailwindcss/cli"]
    sys.exit(
        "Tailwind CLI not found. Run `npm install` in frontend/ first "
        "(@tailwindcss/cli is a devDependency there)."
    )


def sources_fingerprint() -> str:
    """Hash of the inputs, so --check can tell stale from merely reordered."""
    h = hashlib.sha256()
    for p in (HTML, CSS):
        h.update(p.read_bytes())
    return h.hexdigest()[:16]


def compile_css() -> str:
    # --cwd points at frontend/, because that is the only directory in this
    # repo with a node_modules -- without it `@import 'tailwindcss'` cannot
    # resolve from launcher/. The input path and the @source glob inside
    # splash.css stay relative to launcher/, which is where they belong.
    cmd = tailwind_cli() + [
        "--cwd", str(FRONTEND),
        "--input", str(CSS),
        "--minify",
    ]
    proc = subprocess.run(cmd, capture_output=True, text=True, cwd=str(ROOT))
    if proc.returncode != 0:
        sys.exit(f"Tailwind CLI failed:\n{proc.stderr}")
    css = proc.stdout.strip()
    if not css:
        sys.exit("Tailwind CLI produced no CSS.")
    return css


def render(css: str) -> str:
    html = HTML.read_text(encoding="utf-8")
    if PLACEHOLDER not in html:
        sys.exit(f"{HTML.name} no longer contains {PLACEHOLDER}.")
    html = html.replace(PLACEHOLDER, css)

    # The source file carries a comment block explaining that it is the source
    # and is not served. Shipping that to users would be confusing; strip the
    # ones addressed to whoever is editing splash.html.
    html = re.sub(r"\n<!--\n  This file is the SOURCE.*?-->\n", "\n", html, flags=re.S)

    # r""" so the page's own backslashes and \n survive, matching how
    # LOADER_HTML was written when it lived in launcher.py.
    if '"""' in html:
        sys.exit('splash.html contains a triple quote; it cannot be embedded as r""".')
    if html.rstrip().endswith("\\"):
        sys.exit("splash.html ends with a backslash; r\"\"\" cannot end that way.")

    return (
        '"""GENERATED by scripts/build_splash.py -- do not edit.\n'
        "\n"
        "Source: launcher/splash.html + launcher/splash.css\n"
        f"Sources fingerprint: {sources_fingerprint()}\n"
        "\n"
        "Committed on purpose, so a build without npm still produces a working\n"
        "exe. Regenerate with `python scripts/build_splash.py`; CI and build.sh\n"
        "fail if this is stale.\n"
        '"""\n'
        "\n"
        f"SOURCES_FINGERPRINT = {sources_fingerprint()!r}\n"
        "\n"
        'LOADER_HTML = r"""'
        f"{html}"
        '"""\n'
    )


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="fail if the output is stale")
    args = ap.parse_args()

    for p in (HTML, CSS):
        if not p.exists():
            sys.exit(f"missing source: {p.relative_to(ROOT)}")

    if args.check:
        if not OUT.exists():
            print(f"{OUT.relative_to(ROOT)} does not exist. Run scripts/build_splash.py.")
            return 1
        want = sources_fingerprint()
        text = OUT.read_text(encoding="utf-8")
        m = re.search(r"^SOURCES_FINGERPRINT = ['\"]([0-9a-f]+)['\"]", text, re.M)
        have = m.group(1) if m else None
        if have != want:
            print(
                f"{OUT.relative_to(ROOT)} is stale.\n"
                f"  sources: {want}\n"
                f"  bundled: {have}\n"
                "Run `python scripts/build_splash.py` and commit the result."
            )
            return 1
        print(f"OK: {OUT.relative_to(ROOT)} matches its sources ({want}).")
        return 0

    out = render(compile_css())
    OUT.write_text(out, encoding="utf-8")
    css_bytes = len(out.encode("utf-8"))
    print(
        f"wrote {OUT.relative_to(ROOT)}  ({css_bytes:,} bytes, "
        f"fingerprint {sources_fingerprint()})"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
